apiVersion: v1
kind: Service
metadata:
  name: nexus-svc
  namespace: nexus
spec:
  type: LoadBalancer
  ports:
    - name: nexus-ui
      port: 8080
      targetPort: 8080
    - name: jnlp
      port: 50000
      targetPort: 50000
    - port: 80
      targetPort: 8081
      protocol: TCP
      name: http
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: docker 
  selector:
    app: nexus


